Now uses .bind and Drupals context variable instead of the jQuery .on() event binder to be better compatible with older versions of jQuery. Based on the issue [#2291285] by [@gooddesignusa]: Uncaught TypeError: undefined is not a function.